// generated by CommonLibrary.cmake, do not edit.

#include <@INCLUDE_NAME@/version.h>
#include <sstream>

namespace @namespace@
{

int Version::getMajor()
{
    return @NAMESPACE@_VERSION_MAJOR;
}

int Version::getMinor()
{
    return @NAMESPACE@_VERSION_MINOR;
}

int Version::getPatch()
{
    return @NAMESPACE@_VERSION_PATCH;
}

int Version::getABI()
{
    return @NAMESPACE@_VERSION_ABI;
}

std::string Version::getString()
{
    std::ostringstream version;
    version << getMajor() << '.' << getMinor() << '.' << getPatch();
    return version.str();
}

int Version::getRevision()
{
    return @NAMESPACE@_VERSION_REVISION;
}

std::string Version::getRevString()
{
    std::ostringstream version;
    version << getString() << '.' << std::hex << getRevision() << std::dec;
    return version.str();
}

}
